# indian_stocks_list.py

indian_stocks_yf_supported = [
    "TCS", "INFY", "WIPRO", "HDFCBANK", "ICICIBANK", "AXISBANK",
    "KOTAKBANK", "SBIN", "HINDUNILVR", "ITC", "ONGC", "NTPC", "POWERGRID",
    "BHARTIARTL", "BAJFINANCE", "BAJAJFINSV", "ADANIENT", "ADANIPORTS", 
    "HCLTECH", "LT", "TATAMOTORS", "TATASTEEL", "COALINDIA", "SUNPHARMA", 
    "TECHM", "VEDL", "UPL", "BPCL", "IOC", "HEROMOTOCO", "EICHERMOT", 
    "ULTRACEMCO", "GRASIM", "JSWSTEEL", "DIVISLAB", "ASIANPAINT", 
    "CIPLA", "BRITANNIA", "SHREECEM", "MARUTI", "SUZLON"
]
